name: "Deploy pages"

permissions:
  contents: write
  id-token: write
  pages: write
on:
  workflow_dispatch:

jobs:
  dev:
    uses: ./.github/workflows/deploy_branch.yml
    with:
      dev: true
      artifact_prefix: dev
    permissions:
      contents: write
      id-token: write

  master:
    uses: ./.github/workflows/deploy_branch.yml
    with:
      dev: false
      artifact_prefix: master
    permissions:
      contents: write
      id-token: write

  deploy:
    runs-on: ubuntu-latest
    needs: [dev, master]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download MDBook artifacts (dev)
        uses: actions/download-artifact@v5
        with:
          name: dev_mdbook
          path: site/dev/book
      - name: Download rustdoc artifacts (dev)
        uses: actions/download-artifact@v5
        with:
          name: dev_rustdoc
          path: site/dev/doc

      - name: Download MDBook artifacts (master)
        uses: actions/download-artifact@v5
        with:
          name: master_mdbook
          path: site/book
      - name: Download rustdoc artifacts (master)
        uses: actions/download-artifact@v5
        with:
          name: master_rustdoc
          path: site/doc
        
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4